name: Build Vue
on:
<<<<<<< HEAD
  push:
    branches:
      - main
jobs:
  build_vue:
    runs-on: ubuntu-latest
    name: Build Vue
    steps:
      - uses: actions/checkout@v2
      - id: Build-Vue
        uses: xRealNeon/VuePagesAction@1.0.0
        with:
          username: 'IMT-Atlantique-FIL-2020-2023'
          reponame: 'NADA-webapp'
          token: ${{ secrets.GITHUB_TOKEN }}
        env:
          VUE_APP_KEY: ${{ secrets.VUE_APP_KEY }}
          VUE_APP_URL: ${{ secrets.VUE_APP_URL }}
=======
    push:
        branches:
            - main
jobs:
    build_vue:
        runs-on: ubuntu-latest
        name: Build Vue
        steps:
            - uses: actions/checkout@v2
            - id: Build-Vue
              uses: xRealNeon/VuePagesAction@1.0.0
              with:
                  username: 'IMT-Atlantique-FIL-2020-2023'
                  reponame: 'NADA-webapp'
                  token: ${{ secrets.GITHUB_TOKEN }}
              env:
                  VUE_APP_KEY: ${{ secrets.VUE_APP_KEY }}
                  VUE_APP_URL: ${{ secrets.VUE_APP_URL }}
>>>>>>> main
